### ISSUE TITLE
Kernel Flags

### ISSUE THREAD

**Issue by JosephTLucas** [defunctzombie/jetson-nano-image-maker#3]
Great tool, thanks for publishing it! It works well for me in your original configuration.

However, I'm interested in doing some testing where I need specific kernel functionality (ex: `CONFIG_UPROBES` and `CONFIG_BPF_EVENTS`). I can't quite tell where I could make that sort of customization in this process. Since Docker uses the system kernel, I assume it can't be in the `Dockerfile`. (although I did try commenting out the `NVIDIA-l4t-kernel` stuff -- no change). Do you know where I could make that sort of modification? Maybe QEMU?

Thanks!

**Comment by defunctzombie** [comment]
When you say kernel configuration I'm thinking you refer to the kernel that will run on the nano? If that's the case then you wouldn't be looking at the system kernel or QEMU (which only emulates things so we can build the image).

Assuming the configuration you want is built into the kernel that is part of the NVIDIA-l4t-kernel package then I think the place to look would be the `extlinux.conf` file: https://github.com/defunctzombie/jetson-nano-image-maker/blob/main/root/boot/extlinux/extlinux.conf. That's the boot loader configuration and you could set kernel flags there.

If however you need to compile a different kernel - that I have no ideas on but there is a lengthy guide here: https://docs.nvidia.com/jetson/archives/r34.1/DeveloperGuide/text/SD/Kernel.html

I'll close this out as not planned because I think the extlinux.conf file will do what you want with kernel flags and the docs to rebuild a kernel will handle any more exotic configuration. If you do encounter something that this repo could do differently to facilitate the above feel free to re-open or make a new more specific issue.
